### ISSUE TITLE
When no parcels are found, the script fails

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/Cityscape-API-Python-Interface#5]
I think you fixed this earlier, but if there's no parcel found in the `parcels_intersecting` array, the script stops working and throws an error. 

```
[u'http://tod.chicagocityscape.com/tod/index.php?address=153%20BRIARWOOD%20NORTH&city=%20OAK%20BROOK&state=%20IL%2060523']
Traceback (most recent call last):
  File "get-pins.py", line 72, in <module>
    two_closest = get_two_closest(intersecting_parcels[0])
  File "get-pins.py", line 48, in get_two_closest
    two_closest = matches.where(matches.distance_to_centroid.astype(float).nsmallest(1)) # cast distance to float, sort by that, use it in a where clause
  File "/Library/Python/2.7/site-packages/pandas/core/generic.py", line 2672, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'distance_to_centroid'
```

**Comment by easherma** [comment]
resolved
